### ISSUE TITLE
timeouts 

### ISSUE THREAD

**Issue by butterfill** [cogphi/bpd_v8#2]
[from John] the timing is problematic with respect to the 3 second timeout….it should be set up such that if you don’t click start in 3 secs, a message appears, then if you click that a new 3 sec clock starts ticking down, and if you don’t move outside of the start field, a message appears reminding you to do so, and then once you do so the options appear and a NEW 3 sec clock starts ticking down. For some reason it does not work right: If you click start and then move just a bit but don’t leave the start field, then the reminder appears, but then once you leave the start field the clock starts ticking from wherever it left off before you left the start field, so it times out too quickly, leading to unnecessary timeouts.

**Comment by butterfill** [comment]
I can't reproduce this yet: I think that's because there is slightly different code running at different points, so there might be more than one issue with these timeouts.

**Comment by mchennells** [comment]
Fixed in 5f3e6eed3f354f45148ee68139411f6b22178b8c
