### ISSUE TITLE
timeouts : another issue

### ISSUE THREAD

**Issue by butterfill** [cogphi/bpd_v8#4]
In task_1_practice: 

1. I click start (either before or after the reminder to do so; it doesn't matter)
2. I move a bit but stay inside the start field for 2s (so the options do not appear). This is too short to trigger the reminder to move.
3. I move outside the area

**Comment by mchennells** [comment]
(Hopefully) fixed in https://github.com/cogphi/bpd_v8/commit/5f3e6eed3f354f45148ee68139411f6b22178b8c
